language: node_js
node_js:
  - 14.7.0
cache: yarn

isntall:
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
